### ISSUE TITLE
Clicking an Article row in the Article Dashboard Table links to a broken URL

### ISSUE THREAD

**Issue by swar8080** [UPOD-2016/upod_app#1]
When viewing the table of articles in the admin dashboard, clicking on the row for an article brings you to /admin/articles/article_title-id which doesn't exist instead of the correct url of /articles/article_title-id.

By row for an article I mean:
![image](https://cloud.githubusercontent.com/assets/17691679/17425083/89091614-5a97-11e6-8903-bf5893a49244.png)

Thanks

**Comment by ohxx5810** [comment]
Clicking on a a row in order to view an Article leads to an 'ActiveRecord::RecordNotFound' error.
The 'edit' and 'Destroy' links work.  
We need to make the row links work so that it leads straight to the Article for simple viewing,
either that or remove the entire row as a link.

**Comment by K-ODriscoll** [comment]
This should be fixed now. I've tested it and they seem to be working. As long as no other issues arise from my change we should be good!

Try it out for yourselves, let me know any issues.
