### ISSUE TITLE
Sign_in Page

### ISSUE THREAD

**Issue by rmoro** [UPOD-2016/upod_app#10]
## Problem:
Looks like the DIV for the form on the sign_in page is not sized correctly for mobil browsers

## Error:
![image](https://cloud.githubusercontent.com/assets/5367489/17463783/c809e180-5c9b-11e6-8e00-0ac2048e53ac.png)

**Comment by mikeroher** [comment]
Fixed. (https://github.com/UPOD-2016/upod_app/commit/71cdc1a8a6a0ce1487a94d4396a728a78a9cca31)

**Comment by rmoro** [comment]
71cdc1a did not do it for IOS browers see image below (note the time)

![image](https://cloud.githubusercontent.com/assets/5367489/17464039/0cfcdf84-5ca3-11e6-9472-999cf749345a.png)
