### ISSUE TITLE
text-block right after a svg diagram has funny break lines

### ISSUE THREAD

**Issue by ghiyo** [UPOD-2016/upod_app#12]
![screenshot from 2016-08-07 22-39-44](https://cloud.githubusercontent.com/assets/19171509/17467779/df901faa-5cef-11e6-930e-13554c2aadae.png)

**Comment by ghiyo** [comment]
I think I found the issue but I don't know where to go and fix it lol there is a random </div> here and I don't know in which file this is coming from...
![screenshot from 2016-08-08 02-14-29](https://cloud.githubusercontent.com/assets/19171509/17470889/013cbe1a-5d0e-11e6-85ae-6c846f9653f5.png)

**Comment by ghiyo** [comment]
I think I found the issue if you look at the width of the diagram in this article:
![screenshot from 2016-08-08 05-11-35](https://cloud.githubusercontent.com/assets/19171509/17474975/af29ad68-5d26-11e6-87ed-17e7c908ff5a.png)
===========================================================================
and the width of this paragraph:
![screenshot from 2016-08-08 05-11-44](https://cloud.githubusercontent.com/assets/19171509/17474989/bc19cc92-5d26-11e6-9ef3-3631ff3498e1.png)
are the same, some how the diagram is also setting the width of the paragraphs...

**Comment by ghiyo** [comment]
This is also messing up with the footer again.... sad face...
![screenshot from 2016-08-08 05-28-52](https://cloud.githubusercontent.com/assets/19171509/17475451/11e09cc6-5d29-11e6-8bf2-4b6dcc28639a.png)
![screenshot from 2016-08-08 05-29-13](https://cloud.githubusercontent.com/assets/19171509/17475458/167d3a82-5d29-11e6-8f47-1cf745217c90.png)

**Comment by ghiyo** [comment]
All the elements after the diagram seem to be inheriting their attributes from the diagram and not the page itself...

**Comment by swar8080** [comment]
I'm not sure what the issue is here, what do you mean by funny line breaks?

Elements on the page cannot inherit styles from the diagram since the diagram is in an iframe - the browser views them as separate html documents.

All the styling after the diagram looks consistent with what was set in their partials?: https://github.com/UPOD-2016/upod_app/tree/master/app/views/articles/blocks

**Comment by ghiyo** [comment]
this is what I mean
![screenshot from 2016-08-08 09-32-10](https://cloud.githubusercontent.com/assets/19171509/17481398/0592efd8-5d4b-11e6-9251-46e73608c078.png)
As you can see the paragraph above the diagram has a different line break than the paragraph below the diagram. I'm not entirely sure where the issue is though.

**Comment by ghiyo** [comment]
also the footer has white space underneath it meaning min-height is no longer 100%

**Comment by swar8080** [comment]
This seems to be an issue with how diagram blocks were styled (not to be confused with how the actual diagram itself is styled) at https://github.com/UPOD-2016/upod_app/blob/master/app/views/articles/blocks/_diagram_block.html.erb.

My experience with CSS is limited so I'm not sure what to recommend.

**Comment by ghiyo** [comment]
I may have missed a </div> tag lol one second

**Comment by ghiyo** [comment]
yea I forgot to close my div, so sad right now.... lol
