### ISSUE TITLE
width and height options for svg are reverse. If you put 1000 in the width box, it will actually set the height to that number and vice versa

### ISSUE THREAD

**Issue by ghiyo** [UPOD-2016/upod_app#13]
setting width to 150 and height to 300
![screenshot from 2016-08-07 22-42-11](https://cloud.githubusercontent.com/assets/19171509/17467843/4e1fbb24-5cf0-11e6-94b9-b6ecb75ada84.png)
===========================================================================
get width = 300 and height = 150
![screenshot from 2016-08-07 22-42-50](https://cloud.githubusercontent.com/assets/19171509/17467861/66f78e38-5cf0-11e6-9ebb-e9b0556d44a0.png)

**Comment by swar8080** [comment]
This should now be fixed, thanks!
