### ISSUE TITLE
If a link for a video is provided for an article it wont show up in edit page causing the video to disappear after saving

### ISSUE THREAD

**Issue by ghiyo** [UPOD-2016/upod_app#14]
Before editing article contains the link
![screenshot from 2016-08-08 01-23-11](https://cloud.githubusercontent.com/assets/19171509/17469997/b8bbc606-5d06-11e6-90fe-2f4e5749481b.png)
===========================================================================
during editing the link does not show up as saved
![screenshot from 2016-08-08 01-24-30](https://cloud.githubusercontent.com/assets/19171509/17470009/dfc22f1a-5d06-11e6-889b-76bdba518005.png)

**Comment by mikeroher** [comment]
This is probably an issue that I'll have to fix.

**Comment by swar8080** [comment]
This should now be fixed

**Comment by mikeroher** [comment]
Awesome thanks!
