### ISSUE TITLE
Cannot save an equation block without filling in the label

### ISSUE THREAD

**Issue by ghiyo** [UPOD-2016/upod_app#16]

**Comment by K-ODriscoll** [comment]
isn't the label there for a reason, so that we can add a name to the equation? why would we want to save without one?

**Comment by ghiyo** [comment]
Sometimes a user might wanna continue on the next line without anything new to say. But that's not necessary, if you want them to fill the label it should warn them before they save and not mess up the page. Right now if you take out the label and try to save the page it will delete lots of content along with it

**Comment by ghiyo** [comment]
Okay it didn't delete content but it does give an error. Is would be better if it warns the user like how it warns the user not to exceed 1080 width for svg

**Comment by ghiyo** [comment]
Okay I found the situation where content will get deleted. If you have an equation that is saved with a bunch of content after it. If said article is edited by user and the user deletes the label and tries to save it. It will not only give the user the error page, but also it will actually save the article by deleting the equation and every other content that came after it

**Comment by swar8080** [comment]
The label is no longer required since the equation still makes sense without it.

Its also good that you caught that the content was getting deleted. To avoid losing the article if an error is thrown, I've made the update atomic so it reverts the deletion of categories/blocks on any error.
