### ISSUE TITLE
'Sign In' button should not be in final website.

### ISSUE THREAD

**Issue by ohxx5810** [UPOD-2016/upod_app#20]
The 'Sign In' button on the top right should not be shown in the Actual website when it is up.  The option David Brown talked about in class where Admin would have a separate URL to go to admin access would be the best method. The reason for this would not only be for security issues, but the sole purpose of the website is for the Users, and Users will never need the 'Sign In' function.  This will make the website more user-friendly.

**Comment by ghiyo** [comment]
I already removed this
