### ISSUE TITLE
Error while seeding

### ISSUE THREAD

**Issue by ghiyo** [UPOD-2016/upod_app#4]
Starting to create 20 articles
Iteration 1 of 20
ERROR:
================================================
rake aborted!
ActiveRecord::ActiveRecordError: cannot update a new record
/home/malush/upod_app/app/models/article.rb:80:in `set_article_slug'
/home/malush/upod_app/db/seeds.rb:65:in `block in <top (required)>'
/home/malush/upod_app/db/seeds.rb:62:in `times'
/home/malush/upod_app/db/seeds.rb:62:in `<top (required)>'
Tasks: TOP => db:setup => db:seed
(See full trace by running task with --trace)
================================================
error in articles.rb
PROPOSED SOLUTION:
================================================
if new_record?
	return
    else
    	update_column(:slug, title.parameterize)
end
I haven't pushed this because I don't know if this is the right solution since I have no experience in how the back end stuff should work.
================================================

**Comment by K-ODriscoll** [comment]
Error has been fixed since update_slug is no longer needed in the article model.
