### ISSUE TITLE
Article save errors

### ISSUE THREAD

**Issue by ohxx5810** [UPOD-2016/upod_app#5]
Articles will save properly, then later appear to have lost majority of information, other diagrams, equations.  Images still get lost as well

**Comment by rmoro** [comment]
?? I just created the article "The Photoelectric Effect" and the images seemed to save fine.  Can you provide an example?

**Comment by rmoro** [comment]
The problem seems to happen when there are multiple images or equations and the article is being edited.

**Comment by swar8080** [comment]
Hey, is this still an issue? 

Let us know when the bug occurs and what some of the steps are to re-create it.

**Comment by mikeroher** [comment]
I'm going to close this for now. We can re-open if it's still an issue.
