### ISSUE TITLE
Using the search bar with filter errors

### ISSUE THREAD

**Issue by ohxx5810** [UPOD-2016/upod_app#6]
When using the search bar, selecting it's appropriate category results in proper search results.  However, when using 'All' it produces no results.

**Comment by rmoro** [comment]
I just tested this and it does not appear to happen for me

I searched 

"Scalars" first with "All" and got the result "Scalars and vectors"

Then I searched for "Scalars" with "Fundamentals" and it returned the same result.


Closing issue unless you have specific results

**Comment by rmoro** [comment]
Checked this extensively and does not appear to be an issue.  Closing.
