### ISSUE TITLE
Logo resizing issue

### ISSUE THREAD

**Issue by rmoro** [UPOD-2016/upod_app#7]
Front logo does not resize for mobile browsers:

![image](https://cloud.githubusercontent.com/assets/5367489/17459983/44d7439c-5c1f-11e6-98f4-52d08463837e.png)

**EDIT**:

Only seems to happen on the IOS Browser

**Comment by ghiyo** [comment]
It seems to work on my android:

**Comment by rmoro** [comment]
Fixed: 8c90ad7

![image](https://cloud.githubusercontent.com/assets/5367489/17464455/2293a012-5cad-11e6-83a8-bea82e0399d1.png)
