### ISSUE TITLE
Image Upload Error

### ISSUE THREAD

**Issue by rmoro** [UPOD-2016/upod_app#8]
# **WHEN DOES IT HAPPEN:**
When editing an article and trying to add an image.

# **ERROR:**
![image](https://cloud.githubusercontent.com/assets/5367489/17460519/42bc64b6-5c38-11e6-9309-1619855d35ef.png)

**Comment by mikeroher** [comment]
https://github.com/UPOD-2016/upod_app/commit/33483ad685e28489cf3d4bf4d1a304657e3a4804
